/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.ibu.flight.internalws.models.thirdcontract.rebooking;

import com.ctriposs.baiji.rpc.common.types.CheckHealthRequestType;
import com.ctriposs.baiji.rpc.common.types.CheckHealthResponseType;
import com.google.common.util.concurrent.ListenableFuture;
import com.ctrip.soa.caravan.common.delegate.Func;
import com.ctriposs.baiji.rpc.client.ServiceClientBase;
import com.ctriposs.baiji.rpc.client.ServiceLookupException;

@SuppressWarnings("all")
public class FlightOrderRebookingClient extends ServiceClientBase<FlightOrderRebookingClient> implements FlightOrderRebookingClientInterface {

    public static final String ORIGINAL_SERVICE_NAME = "FlightOrderRebooking";

    public static final String ORIGINAL_SERVICE_NAMESPACE = "http://soa.ctrip.com/flight/Order/FlightOrderRebooking/v1";

    public static final String CODE_GENERATOR_VERSION = "WSDL-2.6.7";

    public static final String ORIGINAL_SERVICE_TYPE = "NonSLB";

    private FlightOrderRebookingClient(String baseUri) {
        super(FlightOrderRebookingClient.class, baseUri);
    }

    private FlightOrderRebookingClient(String serviceName, String serviceNamespace, String subEnv) throws ServiceLookupException {
        super(FlightOrderRebookingClient.class, serviceName, serviceNamespace, subEnv);
    }

    public static FlightOrderRebookingClient getInstance() {
        return ServiceClientBase.getInstance(FlightOrderRebookingClient.class);
    }

    public static FlightOrderRebookingClient getInstance(String baseUri) {
        return ServiceClientBase.getInstance(FlightOrderRebookingClient.class, baseUri);
    }

    @Override
    public CheckHealthResponseType checkHealth(CheckHealthRequestType request)
                                        throws Exception {
        return super.invoke("checkHealth",  request, CheckHealthResponseType.class);
    }

    @Override
    public CheckHealthResponseType checkHealth(CheckHealthRequestType request, Func<CheckHealthResponseType> fallbackProvider)
                                        throws Exception {
        return super.invoke("checkHealth",  request, fallbackProvider, CheckHealthResponseType.class);
    }

    @Override
    public ListenableFuture<CheckHealthResponseType> checkHealthAsync(CheckHealthRequestType request)
                                        throws Exception {
        return super.invokeAsync("checkHealth",  request, CheckHealthResponseType.class);
    }

    @Override
    public RebookingDetailSearchResponse rebookingDetailSearch(RebookingDetailSearchRequest request)
                                        throws Exception {
        return super.invoke("rebookingDetailSearch",  request, RebookingDetailSearchResponse.class);
    }

    @Override
    public RebookingDetailSearchResponse rebookingDetailSearch(RebookingDetailSearchRequest request, Func<RebookingDetailSearchResponse> fallbackProvider)
                                        throws Exception {
        return super.invoke("rebookingDetailSearch",  request, fallbackProvider, RebookingDetailSearchResponse.class);
    }

    @Override
    public ListenableFuture<RebookingDetailSearchResponse> rebookingDetailSearchAsync(RebookingDetailSearchRequest request)
                                        throws Exception {
        return super.invokeAsync("rebookingDetailSearch",  request, RebookingDetailSearchResponse.class);
    }
}